# <img src="https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg" width="35" alt="Python Logo"> Stack de Dados Módulo 2 - Limpeza e Filtragem de Dados

Nesta etapa vamos mergulhar no verdadeiro trabalho de quem atua com ciência e engenharia de dados. No módulo anterior nós aprendemos a abrir arquivos e colocar tudo para dentro do computador usando o Pandas. Todavia, bases de dados governamentais e empresariais do mundo real quase nunca chegam prontas para uso. Elas costumam apresentar células vazias, textos misturados com números e colunas que não servem para a nossa análise. Logo, é por isso que a limpeza e a filtragem representam uma etapa importante de qualquer análise de um dataset.

### O que vamos estruturar agora?
Vamos dominar quatro pilares fundamentais para organizar as nossas bases.
* **Filtragem de Linhas:** Isolando apenas as informações que queremos investigar.
* **Tratamento de Dados Nulos:** O que fazer com buracos e células vazias na nossa tabela.
* **Conversão de Tipos (Casting):** Ensinando o computador a diferenciar textos descritivos de números financeiros.
* **Limpeza de Colunas:** Descartando dados inúteis para economizar a memória da máquina.

## 🗂️ Conhecendo nosso Dataset

Neste módulo, vamos explorar os registros oficiais do **Centro de Investigação e Prevenção de Acidentes Aeronáuticos (CENIPA)**. O CENIPA é o órgão responsável por investigar acidentes e incidentes na aviação civil brasileira. Seu foco não é apontar culpados, mas sim identificar os fatores contribuintes para gerar recomendações de segurança e prevenir novas ocorrências no espaço aéreo nacional.

### 📊 O que tem na nossa base de dados?
A base que utilizaremos acompanha todas as ocorrências aeronáuticas notificadas em solo brasileiro desde 2007. Esse conjunto de dados é dividido em algumas tabelas (arquivos CSV) que se conectam. Ao carregar o arquivo principal de ocorrências, você encontrará diversas colunas detalhando os cenários, como:
* **Identificação e Classificação:** Códigos únicos do evento e se foi um incidente ou um acidente.
* **Localização e Data:** Cidade, estado (UF), país, aeródromo, coordenadas geográficas (latitude e longitude), dia e hora.
* **Investigação e Relatórios:** Status da investigação, se a aeronave foi liberada e detalhes sobre a publicação do relatório final.
* **Estatísticas do Evento:** Total de aeronaves envolvidas, total de recomendações geradas e se houve saída de pista.
* **Tabelas Complementares:** Além da tabela principal, a base oficial conta com arquivos extras focados nos Tipos de Ocorrência, Aeronaves, Fatores Contribuintes e Recomendações.

### 📥 Onde acessar os dados?
Para facilitar o andamento do laboratório, os arquivos já estão preparados e formatados para o nosso uso. Você tem duas opções para acessá-los:

1. **Usar o arquivo do repositório:** Se você fez o download ou clonou este projeto, os arquivos já estão no seu computador! Eles se encontram organizados dentro da pasta `arquivos-e-imagens` e se chama [CENIPA_ocorrencias.csv](arquivos-e-imagens/CENIPA_ocorrencias.csv)..
2. **Acessar a fonte oficial:** Caso queira entender como o Governo Federal publica esses dados para a sociedade, consultar o dicionário de variáveis ou baixar bases atualizadas, você pode acessar a página oficial no [Portal de Dados Abertos](https://dados.gov.br/dados/conjuntos-dados/ocorrencias-aeronauticas-da-aviacao-civil-brasileira).

In [4]:
import pandas as pd

# Adicionamos o parametro encoding="latin1" para o Pandas entender os acentos em portugues
tabela_ocorrencias = pd.read_csv("arquivos-e-imagens/CENIPA_ocorrencias.csv", sep=";", encoding="latin1")

# Verifica as primeiras 5 linhas do nosso dataset
tabela_ocorrencias.head()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,88808,88808,88808,88808,88808,INCIDENTE,-23.43555555555,-46.47305555555,GUARULHOS,SP,...,19/04/2026,04:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,88804,88804,88804,88804,88804,INCIDENTE,-23.43555555555,-46.47305555555,GUARULHOS,SP,...,23/04/2026,15:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
2,88794,88794,88794,88794,88794,INCIDENTE,-22.81,-43.25055555555,RIO DE JANEIRO,RJ,...,28/04/2026,18:36:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
3,88783,88783,88783,88783,88783,INCIDENTE,-22.81,-43.25055555555,RIO DE JANEIRO,RJ,...,30/04/2026,19:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
4,88769,88769,88769,88769,88769,INCIDENTE GRAVE,-12.90861111111,-38.3225,SALVADOR,BA,...,09/05/2026,19:15:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,SIM

In [6]:
tabela_ocorrencias.shape

(14626, 22)

In [5]:
# Exibe as ultimas 5 linhas do nosso dataset
tabela_ocorrencias.tail()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
14621,28377,28377,28377,28377,28377,ACIDENTE,***,***,IMPERATRIZ,MA,...,27/01/2007,11:18:00,SIM,FINALIZADA,A-053/CENIPA/2009,SIM,2009-11-16,2,1,NÃO
14622,28375,28375,28375,28375,28375,ACIDENTE,-23.6122222222,-51.385,APUCARANA,PR,...,26/01/2007,18:15:00,SIM,FINALIZADA,A-021/CENIPA/2010,SIM,2007-08-15,1,1,NÃO
14623,28355,28355,28355,28355,28355,ACIDENTE,-17.2541666667,-43.8536111111,BOCAIÚVA,MG,...,18/01/2007,09:10:00,SIM,FINALIZADA,A-001/CENIPA/2010,SIM,2010-03-19,11,1,NÃO
14624,28335,28335,28335,28335,28335,ACIDENTE,-23.3444444444,-51.0633333333,LONDRINA,PR,...,19/01/2007,12:30:00,SIM,FINALIZADA,A-169/CENIPA/2013,SIM,2013-12-16,1,1,NÃO
14625,28256,28256,28256,28256,28256,ACIDENTE,-22.2180555556,-47.1763888889,MOGI GUAÇU,SP,...,07/01/2007,11:30:00,SIM,FINALIZADA,A-112/CENIPA/2012,SIM,2012-10-17,2,1,NÃO

In [8]:
# Filtro inicial
ocorrencias_sp = tabela_ocorrencias[tabela_ocorrencias["ocorrencia_uf"] == "SP"]
ocorrencias_sp.head()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,88808,88808,88808,88808,88808,INCIDENTE,-23.43555555555,-46.47305555555,GUARULHOS,SP,...,19/04/2026,04:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,88804,88804,88804,88804,88804,INCIDENTE,-23.43555555555,-46.47305555555,GUARULHOS,SP,...,23/04/2026,15:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
6,88767,88767,88767,88767,88767,ACIDENTE,-20.6125,-49.08388888888,ALTAIR,SP,...,17/04/2026,02:45:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
8,88765,88765,88765,88765,88765,INCIDENTE GRAVE,-23.62611111111,-46.65638888888,SÃO PAULO,SP,...,30/04/2026,14:33:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,2,NÃO
26,88741,88741,88741,88741,88741,INCIDENTE,-23.62611111111,-46.65638888888,SÃO PAULO,SP,...,23/04/2026,18:10:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [12]:
# Valores Nulos
print("Valores vazios por coluna:")
tabela_ocorrencias.isna().sum()

Valores vazios por coluna:

codigo_ocorrencia                     0
codigo_ocorrencia1                    0
codigo_ocorrencia2                    0
codigo_ocorrencia3                    0
codigo_ocorrencia4                    0
ocorrencia_classificacao              0
ocorrencia_latitude                2941
ocorrencia_longitude               2941
ocorrencia_cidade                     0
ocorrencia_uf                         0
ocorrencia_pais                       0
ocorrencia_aerodromo                  0
ocorrencia_dia                        0
ocorrencia_hora                       2
investigacao_aeronave_liberada        0
investigacao_status                   0
divulgacao_relatorio_numero         646
divulgacao_relatorio_publicado        0
divulgacao_dia_publicacao         12019
total_recomendacoes                   0
total_aeronaves_envolvidas            0
ocorrencia_saida_pista                0
dtype: int64

In [17]:
# Casting
tabela_ocorrencias.dtypes

codigo_ocorrencia                  int64
codigo_ocorrencia1                 int64
codigo_ocorrencia2                 int64
codigo_ocorrencia3                 int64
codigo_ocorrencia4                 int64
ocorrencia_classificacao          object
ocorrencia_latitude               object
ocorrencia_longitude              object
ocorrencia_cidade                 object
ocorrencia_uf                     object
ocorrencia_pais                   object
ocorrencia_aerodromo              object
ocorrencia_dia                    object
ocorrencia_hora                   object
investigacao_aeronave_liberada    object
investigacao_status               object
divulgacao_relatorio_numero       object
divulgacao_relatorio_publicado    object
divulgacao_dia_publicacao         object
total_recomendacoes                int64
total_aeronaves_envolvidas         int64
ocorrencia_saida_pista            object
dtype: object

In [20]:
colunas_apagadas = ["codigo_ocorrencia1", "codigo_ocorrencia2", "codigo_ocorrencia3", "codigo_ocorrencia4", "ocorrencia_pais"]
tabela_filtrada = tabela_ocorrencias.drop(colunas_apagadas, axis=1)
tabela_filtrada.head()

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,88808,INCIDENTE,-23.43555555555,-46.47305555555,GUARULHOS,SP,SBGR,19/04/2026,04:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,88804,INCIDENTE,-23.43555555555,-46.47305555555,GUARULHOS,SP,SBGR,23/04/2026,15:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
2,88794,INCIDENTE,-22.81,-43.25055555555,RIO DE JANEIRO,RJ,SBGL,28/04/2026,18:36:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
3,88783,INCIDENTE,-22.81,-43.25055555555,RIO DE JANEIRO,RJ,SBGL,30/04/2026,19:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
4,88769,INCIDENTE GRAVE,-12.90861111111,-38.3225,SALVADOR,BA,SBSV,09/05/2026,19:15:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,SIM

In [24]:
nomes = {
    "ocorrencia_classificacao" : "ocorrencia_tipo",
    "ocorrencia_uf": "estado",
    "ocorrencia_cidade": "cidade"
}
tabela_filtrada = tabela_filtrada.rename(columns=nomes)
tabela_filtrada.head()

,codigo_ocorrencia,ocorrencia_tipo,ocorrencia_latitude,ocorrencia_longitude,cidade,estado,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,88808,INCIDENTE,-23.43555555555,-46.47305555555,GUARULHOS,SP,SBGR,19/04/2026,04:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,88804,INCIDENTE,-23.43555555555,-46.47305555555,GUARULHOS,SP,SBGR,23/04/2026,15:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
2,88794,INCIDENTE,-22.81,-43.25055555555,RIO DE JANEIRO,RJ,SBGL,28/04/2026,18:36:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
3,88783,INCIDENTE,-22.81,-43.25055555555,RIO DE JANEIRO,RJ,SBGL,30/04/2026,19:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
4,88769,INCIDENTE GRAVE,-12.90861111111,-38.3225,SALVADOR,BA,SBSV,09/05/2026,19:15:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,SIM